### ISSUE TITLE
AssertionError: Task cifar10_ff_attention doesn't exists

### ISSUE THREAD

**Issue by TInaWangxue** [RobertCsordas/linear_layer_as_attention#2]
I have run the run.py by using the command "python3 /linear_layer_as_attention/run.py ./sweeps/ff_as_attention/ff_as_attention_cifar10_10samples.yaml". When it is running, I met this issue:

Traceback (most recent call last):
  File "/linear_layer_as_attention/main.py", line 86, in <module>
    main()
  File "/linear_layer_as_attention/main.py", line 62, in main
    helper, task = initialize()
  File "/linear_layer_as_attention/main.py", line 56, in initialize
    task = tasks.get_task(helper.args.task)
  File "/linear_layer_as_attention/tasks/task_db.py", line 57, in get_task
    assert name in TASKS, f"Task {name} doesn't exists"
AssertionError: Task cifar10_ff_attention doesn't exists

Do I need to modify or configure some args that I forget ?

**Comment by RobertCsordas** [comment]
Thank you for reporting this! Sorry, I accidentally removed that file while cleaning up the code. I added it back now. Please let me know if you have any other issues.
